### ISSUE TITLE
java.lang.NoSuchMethodError: org.scalatra.json.JsonSupport.withRouteMultiParams(Lscala/Option;Lscala/Function0;)Ljava/lang/Object;

### ISSUE THREAD

**Issue by sleshJdev** [scalatra/scalatra#567] opened 2016-04-11 19:25 UTC
Hi. I write simple rest-service with scalatra and have problems with retrieving JSON response.

I doing with [guide](http://scalatra.org/2.4/guides/formats/json.html), but always get error.

Can you help fix this issue? Actually I tried difference versions as described [here](https://groups.google.com/forum/#!topic/scalatra-user/V0dS46b-jfU), but is failed.

Here it is stack trace:
`
java.lang.NoSuchMethodError: org.scalatra.json.JsonSupport.withRouteMultiParams(Lscala/Option;Lscala/Function0;)Ljava/lang/Object;
        at org.scalatra.json.JsonSupport$class.invoke(JsonSupport.scala:82)
        at my.app.web.controller.UserServlet.invoke(UserServlet.scala:17)
        at org.scalatra.ScalatraBase$$anonfun$runFilters$1$$anonfun$apply$6.apply(ScalatraBase.scala:241)
        at org.scalatra.ScalatraBase$$anonfun$runFilters$1$$anonfun$apply$6.apply(ScalatraBase.scala:240)
        at scala.Option.foreach(Option.scala:257)
        at org.scalatra.ScalatraBase$$anonfun$runFilters$1.apply(ScalatraBase.scala:240)
        at org.scalatra.ScalatraBase$$anonfun$runFilters$1.apply(ScalatraBase.scala:239)
        at scala.collection.Iterator$class.foreach(Iterator.scala:742)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1194)
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
        at org.scalatra.ScalatraBase$class.runFilters(ScalatraBase.scala:239)
        at my.app.web.AbstractServlet.runFilters(AbstractServlet.scala:14)
        at org.scalatra.ScalatraBase$$anonfun$runActions$1$1$$anonfun$apply$1.apply$mcV$sp(ScalatraBase.scala:169)
        at org.scalatra.ScalatraBase$$anonfun$runActions$1$1$$anonfun$apply$1.apply(ScalatraBase.scala:163)
        at org.scalatra.ScalatraBase$$anonfun$runActions$1$1$$anonfun$apply$1.apply(ScalatraBase.scala:163)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
        at org.scalatra.DynamicScope$class.withResponse(DynamicScope.scala:78)
        at my.app.web.AbstractServlet.withResponse(AbstractServlet.scala:14)
        at org.scalatra.DynamicScope$$anonfun$withRequestResponse$1.apply(DynamicScope.scala:58)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
        at org.scalatra.DynamicScope$class.withRequest(DynamicScope.scala:69)
        at my.app.web.AbstractServlet.withRequest(AbstractServlet.scala:14)
        at org.scalatra.DynamicScope$class.withRequestResponse(DynamicScope.scala:57)
        at my.app.web.AbstractServlet.withRequestResponse(AbstractServlet.scala:14)
        at org.scalatra.ScalatraBase$$anonfun$runActions$1$1.apply(ScalatraBase.scala:162)
        at org.scalatra.ScalatraBase$$anonfun$runActions$1$1.apply(ScalatraBase.scala:161)
        at org.scalatra.ScalatraBase$$anonfun$runCallbacks$1.apply(ScalatraBase.scala:62)
        at org.scalatra.ScalatraBase$$anonfun$runCallbacks$1.apply(ScalatraBase.scala:62)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at org.scalatra.ScalatraBase$.runCallbacks(ScalatraBase.scala:62)
        at org.scalatra.ScalatraBase$$anonfun$executeRoutes$2$$anonfun$apply$5.apply(ScalatraBase.scala:192)
        at org.scalatra.ScalatraBase$$anonfun$executeRoutes$2$$anonfun$apply$5.apply(ScalatraBase.scala:191)
        at org.scalatra.ScalatraBase$class.org$scalatra$ScalatraBase$$cradleHalt(ScalatraBase.scala:218)
        at org.scalatra.ScalatraBase$$anonfun$executeRoutes$2.apply(ScalatraBase.scala:188)
        at org.scalatra.ScalatraBase$$anonfun$executeRoutes$2.apply(ScalatraBase.scala:187)
        at org.scalatra.ScalatraBase$class.org$scalatra$ScalatraBase$$cradleHalt(ScalatraBase.scala:218)
        at org.scalatra.ScalatraBase$class.executeRoutes(ScalatraBase.scala:187)
        at my.app.web.AbstractServlet.executeRoutes(AbstractServlet.scala:14)
        at org.scalatra.ScalatraBase$$anonfun$handle$1.apply$mcV$sp(ScalatraBase.scala:126)
        at org.scalatra.ScalatraBase$$anonfun$handle$1.apply(ScalatraBase.scala:126)
        at org.scalatra.ScalatraBase$$anonfun$handle$1.apply(ScalatraBase.scala:126)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
        at org.scalatra.DynamicScope$class.withResponse(DynamicScope.scala:78)
        at my.app.web.AbstractServlet.withResponse(AbstractServlet.scala:14)
        at org.scalatra.DynamicScope$$anonfun$withRequestResponse$1.apply(DynamicScope.scala:58)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
        at org.scalatra.DynamicScope$class.withRequest(DynamicScope.scala:69)
        at my.app.web.AbstractServlet.withRequest(AbstractServlet.scala:14)
        at org.scalatra.DynamicScope$class.withRequestResponse(DynamicScope.scala:57)
        at my.app.web.AbstractServlet.withRequestResponse(AbstractServlet.scala:14)
        at org.scalatra.ScalatraBase$class.handle(ScalatraBase.scala:125)
        at my.app.web.AbstractServlet.org$scalatra$servlet$ServletBase$$super$handle(AbstractServlet.scala:14)
        at org.scalatra.servlet.ServletBase$class.handle(ServletBase.scala:53)
        at my.app.web.AbstractServlet.org$scalatra$scalate$ScalateSupport$$super$handle(AbstractServlet.scala:14)
        at org.scalatra.scalate.ScalateSupport$class.handle(ScalateSupport.scala:152)
        at my.app.web.AbstractServlet.handle(AbstractServlet.scala:14)
        at org.scalatra.ScalatraServlet$class.service(ScalatraServlet.scala:60)
        at my.app.web.AbstractServlet.service(AbstractServlet.scala:14)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:751)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:566)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:578)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1111)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:498)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:183)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1045)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:199)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:109)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:98)
        at org.eclipse.jetty.server.Server.handle(Server.java:461)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:284)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:244)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:534)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:607)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:536)
        at java.lang.Thread.run(Thread.java:745)
`

**Comment by mescam** [comment] 2016-05-16 23:26
The issue is still present with 2.4.1 version.

**Comment by sleshJdev** [comment] 2016-05-17 06:51
I have succeeded fix the error with following configuration:
`"org.json4s" %% "json4s-jackson" % "3.3.0.RC2",`
`"org.scalatra" %% "scalatra-json" % "2.4.0-RC2-2",`

**Comment by itsraghz** [comment] 2016-05-21 11:47
Hi,
  As per [this](https://groups.google.com/forum/#!topic/scalatra-user/V0dS46b-jfU) thread in Google Groups, I have reverted the **Scalatra Version** to be of **2.4.0.RC1** in the build.scala file. Restarted SBT and it worked fine.

**Comment by steve-federowicz** [comment] 2016-09-19 17:42
+1 @sleshJdev updated the packages and it now works.  Thank you!!!

**Comment by magnolia-k** [comment] 2020-03-14 14:50
This issue is closed because it seems to be resolved by the update.

**Closed by magnolia-k** 2020-03-14 14:50 UTC
