### ISSUE TITLE
Why the client can not connect to the server?

### ISSUE THREAD

**Issue by ghost** [scalatra/scalatra#890] opened 2019-03-15 21:01 UTC
Hi all 
Would be nice if someone could help me https://stackoverflow.com/questions/55190367/why-the-client-can-not-connect-to-the-server 

Thanks

**Comment by treaz** [comment] 2019-12-04 10:40
As commented in the stackoverflow thread:
your question is missing important bits of information: 

- What makes you think that this issue is related to scalatra&atmosphere? 
- What happens when you try to use a different WebSockets client? 
- Can you share a demo project that anyone can download and see the error that you're seeing? - What libs&versions are you using?

**Comment by treaz** [comment] 2019-12-04 10:42
Also, why raise an issue here when you're not sure yet whether the problem is in the WS client or the WS server?

**Comment by treaz** [comment] 2019-12-04 10:45
@takezoe can we close this issue?

**Closed** 2020-02-15 02:11 UTC

**Comment by takezoe** [comment] 2020-02-15 02:17
@treaz Thanks for handling this. We can close this issue since no feedback from the inquirer.
