### ISSUE TITLE
Looks likes docs are broken

### ISSUE THREAD

**Issue by beachygreg** [scalatra/scalatra#843] opened 2018-07-17 20:14 UTC
http://www.scalatra.org/ returns some "pending verification per ICANN " page.

**Comment by takezoe** [comment] 2018-07-20 05:28
Hmm... The website is still inactive.

**Comment by mycaule** [comment] 2018-07-21 17:55
Website is still down.

**Comment by mycaule** [comment] 2018-07-22 17:43
For those who don't know,

sources in Markdown format are here https://github.com/scalatra/scalatra-website
You can run locally with `hugo`

And there is code samples in the scalatra Github organization.

**Comment by takezoe** [comment] 2018-07-25 14:17
@mycaule Thanks for letting everyone know. I'm considering to move the domain of the scalatra website to the default domain of GitHub pages (scalatra.github.io).

**Comment by rossabaker** [comment] 2018-07-25 19:58
I verified it on July 16, but it apparently didn't take effect, and now it won't send me another verification.  I opened a support ticket with the registrar today.

**Comment by rossabaker** [comment] 2018-07-26 04:01
I got a verification challenge which gave me an error, but scalatra.org is back up for me.  

I'm closing this as resolved, but not with great confidence since the registrar is acting weirdly.  If still sees the problem, please reopen and I'll look again.

**Closed by rossabaker** 2018-07-26 04:01 UTC

**Comment by takezoe** [comment] 2018-07-26 04:47
@rossabaker I confirmed the website is back. Thanks a lot!
