### ISSUE TITLE
NullPointerException on JacksonJsonSupport on 2.4.0.M3

### ISSUE THREAD

**Issue by hkupty** [scalatra/scalatra#486] opened 2015-03-27 20:56 UTC
I'm experiencing a NullPointerException when I try to start a `ScalatraServlet` with `JacksonJsonSupport`, probably due to 3ab5a658e4321d7a72d5bcde737efa4bd4dd158a, as the stacktrace points:
```
java.lang.NullPointerException
        at org.scalatra.json.JacksonJsonSupport$class.$init$(Jackson.scala:12)
```
I just downgraded back to `2.4.0.M2`, but if I can help with anything, please let me know.

**Comment by seratch** [comment] 2015-04-14 22:56
I'll fix this till RC1.

**Comment by dozed** [comment] 2015-04-15 16:43
@hkupty Can you show how to reproduce this?

**Comment by hkupty** [comment] 2015-04-15 19:08
Well, I have two projects using scalatra for the REST API and I tried now `2.4.0.M3` on both projects.
The issue happened with only one - the simpler.

I don't really know what is causing the issue, but it happens at the servlet initialization.
Despite the exception, the Jetty server starts, but returning only `HTTP 503` for any resource I try to `GET|POST`.

I'll try to isolate what is causing this initialization exception and post here as soon as I find something..

**Comment by hkupty** [comment] 2015-04-15 20:33
>Well, I have two projects using scalatra for the REST API and I tried now 2.4.0.M3 on both projects.
The issue happened with only one - the simpler.

I probably did something wrong when I said that one of the projects works, actually both projects break with the current version.

Both projects are somewhat like the tutorial said (`JettyLauncher` is the same, `ScalatraBootstrap` only mounting the Controller and the Controllers with JacksonJsonSupport pretty much like the example...)

I cannot really say whats breaking it and its pretty much as I said earlier: It breaks on Jetty's init, exception gets logged on the terminal, every operation gives `HTTP 503`.

Maybe I mislead you when I pointed out the commit, as the problem may be with `mapper` or `jsonFormats` being already previously null and 3ab5a658e4 just tried accessing the null pointer...

**Comment by seratch** [comment] 2015-04-16 04:56
@hkupty Could you investigate which is null in your applications, `mapper` or `jsonFormats`? 

I guess the `jsonFormats` somehow may be null. If so, we can choose `false` as the default value in such a case. see also: https://github.com/json4s/json4s/blob/v3.3.0.RC1/core/src/main/scala/org/json4s/Formats.scala#L46

**Comment by hkupty** [comment] 2015-04-16 17:55
@seratch Sorry for the delay, I just checked that jsonFormats is null and mapper is correctly allocated.

**Comment by hkupty** [comment] 2015-04-16 18:04
Wouldn't it be necessary to define jsonFormats, to import it or to implicitly pass it?

**Comment by seratch** [comment] 2015-04-17 01:57
`jsonFormats` is abstract method in `JValueResult`. Your applications should override the method somewhere. At first, I thought we should fix the initialization error. But this issue looks a little bit strange because returning JSON responses doesn't work when the `jsonFormats` is null. I'd like to close my PR which contains null checks. https://github.com/scalatra/scalatra/pull/494

**Comment by hkupty** [comment] 2015-04-17 02:57
@seratch I define `jsonFormats` as an `implicit val` when defining the `Controller`, as stated in http://www.scalatra.org/2.3/guides/formats/json.html

AFAIK, it happens since `mapper` is trying to access `jsonFormats` **before** its definition, on the controller body..

**Comment by seratch** [comment] 2015-04-17 12:08
>AFAIK, it happens since mapper is trying to access jsonFormats before its definition, on the controller body..

I see. Thanks. I'll work on the issue this weekend.

**Comment by hkupty** [comment] 2015-04-17 12:10
:+1:

**Comment by seratch** [comment] 2015-04-18 02:02
@hkupty I just tried to reproduce your situation. But I couldn't easily do that. If you have time, would you share us a minimum example application which shows that?

**Comment by dozed** [comment] 2015-04-18 15:41
I think this is due to Scala's order of a class hierarchy (linearization). In the testcase the `jsonFormats` value is defined in the trait and evaluated before the mapper is configured. When the `jsonFormats` is defined on the class, it is evaluated last and leads to a NPE during initialization.

**Comment by dozed** [comment] 2015-04-18 15:42
Here is a good read http://jim-mcbeath.blogspot.de/2009/08/scala-class-linearization.html

**Comment by dozed** [comment] 2015-04-19 13:58
This is a test case which shows the NPE: https://github.com/dozed/scalatra/commit/a797a22e78d0b3d01d4a84ef287fc8b6956259a3

**Comment by seratch** [comment] 2015-05-14 15:01
@hkupty 

As @dozed suggested, how about using `lazy val` instead? If it's fine for you, we'd like to close this issue.

**Comment by hkupty** [comment] 2015-05-14 17:27
@seratch I'll check if it solves the issue, but presumably, yes, it looks like a solution.
Nevertheless, having this solved as sugested, the documentation should be updated to inform that.

**Comment by dozed** [comment] 2015-05-14 17:39
I can try to take a look at it, but I am currently short with time also. Let's keep the ticket open until we find a better solution?

**Comment by seratch** [comment] 2015-05-14 22:46
Thanks.

>the documentation should be updated to inform that.

That's true. I'll do that later.

>Let's keep the ticket open until we find a better solution?

OK, I think it's good.

**Closed** 2015-05-24 18:56 UTC
Labels: bug

**Comment by futurechimp** [comment] 2015-05-28 16:21
Note: I've added the `lazy val` marking to all the `jsonFormats` in the 2.4.x versions of the Scalatra Guides, e.g. http://scalatra.org/2.4/guides/formats/json.html
